services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - gateway
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  gatewayservice:
    image: gatewayimage
    container_name: gatewayservice
    ports:
      - "8080:8080"
    networks:
      - gateway
    depends_on:
      mysql-db:
        condition: service_healthy

  clientservice:
    image: clientimage
    container_name: clientservice
    ports:
      - "8081:8081"
    networks:
      - gateway
    depends_on:
      mysql-db:
        condition: service_healthy

  vehiculesservice:
    image: vehiculesimage
    container_name: vehiculesservice
    ports:
      - "8082:8082"
    networks:
      - gateway
    depends_on:
      mysql-db:
        condition: service_healthy

  locationservice:
    image: locationimage
    container_name: locationservice
    ports:
      - "8083:8083"
    networks:
      - gateway
    depends_on:
      mysql-db:
        condition: service_healthy

networks:
  gateway:
    driver: bridge

volumes:
  mysql-data:
