services:
  gatewayservice:
    image: gatewayimage
    container_name: gatewayservice
    ports:
      - "8080:8080"
    networks:
      - gateway

  clientservice:
    image: clientimage
    container_name: clientservice
    ports:
      - "8081:8081"
    networks:
      - gateway

  vehiculesservice:
    image: vehiculesimage
    container_name: vehiculesservice
    ports:
      - "8082:8082"
    networks:
      - gateway

  locationservice:
    image: locationimage
    container_name: locationservice
    ports:
      - "8083:8083"
    networks:
      - gateway

networks:
  gateway:
    driver: bridge
